name: Deploy Reports to GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install markdown  # para converter .md -> .html

      - name: Inject OPENAI_API_KEY
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Generate reports (MD + README + PDF)
        run: |
          python src/report_hybrid.py
          python src/export_readme.py
          python src/export_pdf.py

      - name: Build static site (public/)
        run: |
          mkdir -p public
          # converte o hybrid.md em index.html simples
          python - << 'PY'
import markdown, pathlib
md = pathlib.Path("outputs/hybrid.md").read_text(encoding="utf-8")
html = markdown.markdown(md, extensions=["tables"])
template = f"""<!doctype html>
<html lang="pt-br"><head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Relatório - Customer Feedback</title>
<style>
body{{font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; padding: 24px; max-width: 900px; margin: auto; line-height:1.55}}
table{{border-collapse:collapse; width:100%}}
td,th{{border:1px solid #ccc; padding:8px}}
code,pre{{background:#f6f8fa; padding:4px 6px; border-radius:6px}}
a.button{{display:inline-block; padding:10px 14px; border:1px solid #444; border-radius:8px; text-decoration:none}}
</style>
</head><body>
<h1>📊 Customer Feedback Reports</h1>
<p><a class="button" href="./report.pdf" target="_blank">Baixar PDF</a></p>
<hr/>
{html}
</body></html>"""
pathlib.Path("public/index.html").write_text(template, encoding="utf-8")
PY
          # copia o PDF para o site
          cp outputs/report.pdf public/report.pdf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

