name: Deploy Reports to GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install markdown reportlab

      - name: Check OPENAI secret present
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "::error::Secret OPENAI_API_KEY ausente em Settings → Secrets → Actions."
            exit 1
          fi

      - name: Create .env from secret
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Generate reports (MD + README + PDF)
        run: |
          set -e
          python src/report_hybrid.py
          python src/export_readme.py
          python src/export_pdf.py

	- name: Ensure outputs/hybrid.md exists (fallback)
        run: |
          mkdir -p outputs
          if [ ! -f outputs/hybrid.md ]; then
            printf '# Customer Feedback Report (fallback)\n\nGeração via LLM falhou no CI. Este arquivo garante a publicação do site.\n' > outputs/hybrid.md
          fi
          echo 'Conteúdo de outputs/:'
          ls -la outputs


      - name: Build static site (public/)
        run: |
          mkdir -p public
          python -c "import markdown, pathlib; md=pathlib.Path('outputs/hybrid.md').read_text(encoding='utf-8'); html=markdown.markdown(md, extensions=['tables']); pathlib.Path('public/index.html').write_text('<!doctype html><meta charset=utf-8><title>Relatório</title><a href=./report.pdf target=_blank>Baixar PDF</a><hr>'+html, encoding='utf-8')"
          cp outputs/report.pdf public/report.pdf || echo 'sem PDF'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
