name: Generate Reports

on:
  schedule:
    # 12:00 UTC ≈ 09:00 America/Sao_Paulo
    - cron: "0 12 * * *"
  workflow_dispatch: {}  # permite rodar manualmente

permissions:
  contents: write   # necessário para o 'git push' no fim

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env from secret
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Generate hybrid report
        run: |
          python src/report_hybrid.py

      - name: Update README.md
        run: |
          python src/export_readme.py

      - name: Export PDF
        run: |
          python src/export_pdf.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md outputs/*.md outputs/*.pdf 2>/dev/null || true
          git diff --cached --quiet || git commit -m "chore(ci): atualizar relatórios (CI)"
          git push

